### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 'export' (at es-module-shims.js:2:1)

### ISSUE THREAD

**Issue by schlichtanders** [jspm/generator.jspm.io#43]
The automatically inserted import of es-module-shims (inserted when using `jspm link`)
```html
<script async src="https://esm.sh/*es-module-shims@1.8.3/dist/es-module-shims.js" crossorigin="anonymous"></script>
```
leads to an error in brave (chrome-based)

```
Uncaught SyntaxError: Unexpected token 'export' (at es-module-shims.js:2:1)
```

(EDIT: when adding the `type="module"` manually, I get another error `An import map is added after module script load was triggered.`)

**Comment by guybedford** [comment]
I've transferred this issue to the `generator.jspm.io` issue queue, the problem is that that `esm.sh` requires a separate URL system for referencing es-module-shims here.

In the mean time, you can manually update the URL to https://esm.sh/v135/es-module-shims@1.8.3/es2022/dist/es-module-shims.js.
